# name: ğŸ³ docker-CI

# on:
#   push
   


# jobs:
#     test-ci-Docker:
#         runs-on: ubuntu-latest
#         steps:
#             - name: ğŸ¤— Hello CI
#               run: echo  "This job's status is ${{ job.status }}."

#     docker:
#         needs: test-ci-Docker
#         runs-on: ubuntu-latest
#         steps:
#           - name: ğŸ¦… Set up QEMU
#             uses: docker/setup-qemu-action@v2

#           - name: ğŸ³ Set up Docker Buildx
#             uses: docker/setup-buildx-action@v2

#           - name: ğŸ” Login to Docker Hub
#             uses: docker/login-action@v2
#             with:
#               username: ${{ secrets.DOCKERHUB_USERNAME }}
#               password: ${{ secrets.DOCKERHUB_TOKEN }}

#           - name: ğŸ”¨ Build and push
#             uses: docker/build-push-action@v4
#             with:
#               push: true
#               context: "{{defaultContext}}:front"
#               tags: "${{ secrets.DOCKERHUB_USERNAME }}/test-docker-ci:latest"